version: '3.9'

services:
        ############## KAMAILIO ##################
        fhoss:
                build: ./fhoss
                image: kamailio_fhoss_docker
                container_name: kamailio_fhoss
                expose:
                        - "8080/tcp"
                        - "3868/tcp"
                        - "3868/udp"
                ports:
                        - "8080:8080/tcp"
                env_file: 
                        - .env
                volumes:
                        - ./fhoss/fhoss_conf:/mnt
                depends_on: 
                        mysql:
                                condition: service_healthy
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_FHOSS_IP}
                                aliases: 
                                        - hss
                                        - kamailiohss.ims.mnc001.mcc001.3gppnetwork.org
        srsran:
                build: ./srsran
                image: kamailio_srsran_docker
                tty: true
                stdin_open: true
                container_name: kamailio_srsran
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_SRSRAN_IP}
                env_file:
                        - .env
        sip:
                build: ./sip
                image: kamailio_sip_docker
                tty: true
                stdin_open: true
                container_name: kamailio_sipp
                expose:
                        - "3061/udp"
                        - "3062/udp"
                cap_add:
                        - NET_ADMIN
                privileged: true
                env_file:
                        - .env
                volumes: 
                        - ./sip:/mnt
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_SIP_IP}
        sip2:
                build: ./sip
                image: kamailio_sip_docker
                tty: true
                stdin_open: true
                container_name: kamailio_sipp_2
                expose:
                        - "3061/udp"
                        - "3062/udp"
                cap_add:
                        - NET_ADMIN
                privileged: true
                env_file:
                        - .env
                volumes: 
                        - ./sip:/mnt
                networks:
                        appnet:
                                ipv4_address: 10.1.1.50
        pcscf:
                build: ./kamailio_docker
                image: kamailio_docker
                container_name: kamailio_pcscf
                cap_add:
                        - NET_ADMIN
                privileged: true
                tty: true 
                stdin_open: true
                volumes:
                        - ./kamailio_docker/pcscf:/mnt
                env_file:
                        - .env
                environment:
                        - KAMAILIO_COMPONENT=pcscf
                depends_on: 
                        mysql:
                                condition: service_healthy
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_PCSCF_IP}
                                aliases:
                                        - pcscf
                                        - pcscf.ims.mnc001.mcc001.3gppnetwork.org
        mysql: 
                image: mysql:5.7
                container_name: mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=${KAMAILIO_MYSQL_PWD}
                tty: true
                stdin_open: true
                env_file:
                        - .env
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_MYSQL_IP}
                expose:
                        - "3306/tcp"
                healthcheck:
                        test: ["CMD", "mysql", "-u", "root", "-proot"]
                        timeout: 10s
                        interval: 10s
        icscf:
                image: kamailio_docker
                environment:
                        - KAMAILIO_COMPONENT=icscf
                env_file:
                        - .env
                container_name: kamailio_icscf
                dns: 
                        - 8.8.8.8
                        - ${DNS_IP}
                dns_search:
                        - ims.mnc001.mcc001.3gppnetwork.org
                tty: true
                stdin_open: true
                volumes:
                        - ./kamailio_docker/icscf:/mnt
                depends_on: 
                        - pcscf
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_ICSCF_IP}
                                aliases: 
                                        - icscf
                                        - icscf.ims.mnc001.mcc001.3gppnetwork.org
        scscf:
                tty: true
                stdin_open: true
                dns:
                        - 8.8.8.8
                        - ${DNS_IP}
                dns_search:
                        - ims.mnc001.mcc001.3gppnetwork.org
                environment:
                        - KAMAILIO_COMPONENT=scscf
                image: kamailio_docker
                env_file:
                        - .env
                container_name: kamailio_scscf
                volumes:
                        - ./kamailio_docker/scscf:/mnt
                depends_on: 
                        - pcscf
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_SCSCF_IP}
                                aliases:
                                        - scscf
                                        - scscf.ims.mnc001.mcc001.3gppnetwork.org
        rtpengine:
                networks:
                        appnet:
                                ipv4_address: ${KAMAILIO_RTP_IP}
                tty: true
                stdin_open: true
                expose:
                        - "2223/tcp"
                privileged: true
                environment:
                        - TABLE=0
                        - INTERFACE=${KAMAILIO_RTP_IP}
                        - LISTEN_NG=${KAMAILIO_RTP_IP}:2223
                        - PIDFILE=/run/ngcp-rtpengine-daemon.pid
                        - PORT_MAX=50000
                        - PORT_MIN=49000
                        - NO_FALLBACK=no
                        - TOS=184
                build: ./rtpengine
                container_name: kamailio_rtpengine
                volumes: 
                        - ./rtpengine:/mnt
        ############ END KAMAILIO ##############
        dns:
                networks:
                        appnet:
                                ipv4_address: ${DNS_IP}
                                aliases:
                                        - dns
                tty: true
                stdin_open: true
                build: ./dns
                env_file:
                        - .env
                container_name: kamailio_dns
                volumes: 
                        - ./dns/dns_conf:/mnt

networks:
        appnet:
                name: open5gs_appnet
                #ipam:
                #        config:
                #                - subnet: ${NETWORK_SUBNET}
