FROM ubuntu:bionic
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update 
RUN apt install -y libcurl4-gnutls-dev bison curl debhelper cdbs lintian build-essential fakeroot devscripts pbuilder dh-make debootstrap dpatch flex libxml2-dev libmysqlclient15-dev ant docbook-to-man ipsec-tools subversion
